<a href="https://colab.research.google.com/github/Sanjeev00001/Machine-Learning-2/blob/main/machine_learning_basic_functions_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
pip install numpy

In [ ]:
a=[1,2,'a',2.3]

In [ ]:
prnt(type(a))

NameError: name 'prnt' is not defined

In [ ]:
print(type(a))

<class 'list'>


In [ ]:
print(type([0]))

<class 'list'>


In [ ]:
a1=np.array(a)

In [ ]:
print(type(a1))

<class 'numpy.ndarray'>


In [ ]:
print(a1)

['1' '2' 'a']


In [ ]:
print(a)

[1, 2, 'a']


In [ ]:
len(a1)

3

In [ ]:
np.shape(a1)

(3,)

In [ ]:
a=np.array(([1,2,3][4,5,6][7,8,9]))

<>:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
<>:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
<ipython-input-14-2cdd70f192a2>:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
  a=np.array(([1,2,3][4,5,6][7,8,9]))


TypeError: list indices must be integers or slices, not tuple

In [ ]:
a=np.array([[1,2,3][4,5,6][7,8,9]])

<>:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
<>:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
<ipython-input-15-30e90c4c3d83>:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
  a=np.array([[1,2,3][4,5,6][7,8,9]])


TypeError: list indices must be integers or slices, not tuple

In [ ]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [ ]:
print(np.shape(a))

(3, 3)


In [ ]:
print(len(a))

3


In [ ]:
print(np.size(a))

9


In [ ]:
=np.reshape(a,(1,9))

SyntaxError: invalid syntax (<ipython-input-20-e679e935228e>, line 1)

In [ ]:
b=np.reshape(a,(1,9))

In [ ]:
print(b)

[[1 2 3 4 5 6 7 8 9]]


In [ ]:
c=np.reshape(a,(9,1))

In [ ]:
print(c)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [ ]:
a=np.zeros((5,))

In [ ]:
print(a)

[0. 0. 0. 0. 0.]


In [ ]:
a=np.zeros((5,4),dtype='int16')

In [ ]:
print(a
      )

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [ ]:
b=np.ones((4,))


In [ ]:
b

array([1., 1., 1., 1.])

In [ ]:
b=np.ones((2,3,4))

In [ ]:
b

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [ ]:
b=np.ones((2,4,3))

In [ ]:
b

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [ ]:
c=np.random((2,4))

TypeError: 'module' object is not callable

In [ ]:
c=np.random.random(2,4)

TypeError: random() takes at most 1 positional argument (2 given)

In [ ]:
c=np.random.random((2,4))

In [ ]:
c

array([[0.77237954, 0.18677645, 0.87108123, 0.58965812],
       [0.90365051, 0.94575622, 0.05441263, 0.35189083]])

In [ ]:
c=np.random.random((2,4),dtype='int16')

TypeError: random() got an unexpected keyword argument 'dtype'

In [ ]:
a=[1,2,3,4]
b=[5,6,7,8]

In [ ]:
c=a+b

[1, 2, 3, 4, 5, 6, 7, 8]


In [ ]:

a=np.array(a)
b=np.array(b)
c=a+b


In [ ]:
c

array([ 6,  8, 10, 12])

In [ ]:
d=a-b
e=a*b
print(d)
print(e)

[-4 -4 -4 -4]
[ 5 12 21 32]


In [ ]:
a=np.array([[1,2,3],[4,5,6],7,8,9])
b=np.array([[2,3],[4,5],[5,6]])

<ipython-input-46-83197b2f23ec>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  a=np.array([[1,2,3],[4,5,6],7,8,9])


In [ ]:
c=a@b

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 5)

In [ ]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
b=np.array([[2,3],[4,5],[5,6]])

In [ ]:
c=a*b

ValueError: operands could not be broadcast together with shapes (3,3) (3,2) 

In [ ]:
c=a@b

In [ ]:
print(c)

[[ 25  31]
 [ 58  73]
 [ 91 115]]


In [ ]:
c1=np.dot(a,b)

In [ ]:
print(c1)

[[ 25  31]
 [ 58  73]
 [ 91 115]]


In [ ]:
np.mod(10,2)

0

In [ ]:
a=np.arange(1,9,3)

In [ ]:
print(a)

[1 4 7]


In [ ]:
a=np.linespace(1,10,10)

AttributeError: module 'numpy' has no attribute 'linespace'

In [ ]:
a=np.linspace(1,10,10)

In [ ]:
print(a)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [ ]:
a=np.linspace(1,10,20)

In [ ]:
print(a)

[ 1.          1.47368421  1.94736842  2.42105263  2.89473684  3.36842105
  3.84210526  4.31578947  4.78947368  5.26315789  5.73684211  6.21052632
  6.68421053  7.15789474  7.63157895  8.10526316  8.57894737  9.05263158
  9.52631579 10.        ]


In [ ]:
a=np.array([1,2,3,4,5,6])
np.sum(a)


21

In [ ]:
a=np.array([[1,2,3],[4,5,6],[7,8,9],[1,2,3]])
np.sum(a)


51

In [ ]:
np.shape(a)

(4, 3)

In [ ]:
np.sum(a,axis=0)


array([13, 17, 21])

In [ ]:
np.sum(a,axis=1)


array([ 6, 15, 24,  6])

In [ ]:
np.mean(a)

4.25

In [ ]:
np.meam(a,axis=0)

AttributeError: module 'numpy' has no attribute 'meam'

In [ ]:
np.mean(a,axis=0)


array([3.25, 4.25, 5.25])

In [ ]:
np.std(a,axis=0)


array([2.48746859, 2.48746859, 2.48746859])

In [ ]:
np.std(a)


2.6180463454008347

In [ ]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
b=np.array([1,2,3])
c=a+b
print(c)

[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]


In [ ]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
b=np.array([1,2,3],[2,3,4])
c=a+b
prnt(c)


TypeError: Field elements must be 2- or 3-tuples, got '2'

In [ ]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
b=np.array([1,2,3],[2,3,4])
c=a+b
print(c)

TypeError: Field elements must be 2- or 3-tuples, got '2'

In [ ]:
import pandas as pd

In [ ]:
a=pd.Series([1,2,3,4])
print(type(a))

<class 'pandas.core.series.Series'>


In [ ]:
b=pd.DataFrame([1,2,3,4],[4,5,6])
print(b)

ValueError: Shape of passed values is (4, 1), indices imply (3, 1)

In [ ]:
b=pd.DataFrame([[1,2,3,4],[4,5,6]])
print(b)

   0  1  2    3
0  1  2  3  4.0
1  4  5  6  NaN


In [ ]:
print(type(a))

<class 'pandas.core.series.Series'>


In [ ]:
from google.colab import files
files=files.upload()

Saving pandas file.xlsx to pandas file.xlsx


In [ ]:
df=pd.read_csv(/content/pandas file.xlsx)

SyntaxError: invalid syntax (<ipython-input-81-411c09b9d047>, line 1)

In [ ]:
df=pd.read_csv('/content/pandas file.xlsx')

UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 15-16: invalid continuation byte

In [ ]:
df=pd.read_csv('/content/pandas file.xlsx')

UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 15-16: invalid continuation byte

In [ ]:
df=pd.read_csv('/content/pandas file.xlsx')

UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 15-16: invalid continuation byte

In [ ]:
from google.colab import files
files=files.upload()

Saving pandas file.xlsx to pandas file.xlsx


In [ ]:
from google.colab import files
files=files.upload()

Saving demo.csv to demo.csv


In [ ]:
df=pd.read_csv('/content/demo.csv')

In [ ]:
print(df)

   Sr. no.    Name               Email  CGPA
0      1.0  sanjeev  sanjeev@gmail.com   8.0
1      2.0      lpu      lpu@gmail.com   9.0
2      NaN      NaN                NaN   NaN
