<a href="https://colab.research.google.com/github/Sanjeev00001/Machine-Learning-2/blob/main/Q_table_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
# Hyperparameters
GRID_SIZE = 3
NUM_ACTIONS = 4
LEARNING_RATE = 0.1
DISCOUNT_FACTOR = 0.9  # Define discount factor
NUM_EPISODES = 1000
EPSILON = 0.1  # Exploration rate

# Define the rewards and the environment
rewards = np.array([[-1, -1, -1],
                    [-1, -5, -1],
                    [-1, -1, 10]])  # Negative rewards except for goal

# Initialize Q-table with zeros
Q_table = np.zeros((GRID_SIZE, GRID_SIZE, NUM_ACTIONS))

def q_learning():
    for episode in range(NUM_EPISODES):
        state = (0, 0)  # Start at the top-left corner
        while state != (2, 2):  # Until reaching the goal
            # Epsilon-greedy action selection
            if np.random.rand() < EPSILON:
                action = np.random.randint(NUM_ACTIONS)  # Explore
            else:
                action = np.argmax(Q_table[state])  # Exploit

            # Determine the next state based on action
            next_state = state
            if action == 0 and state[0] > 0:  # Up
                next_state = (state[0] - 1, state[1])
            elif action == 1 and state[0] < GRID_SIZE - 1:  # Down
                next_state = (state[0] + 1, state[1])
            elif action == 2 and state[1] > 0:  # Left
                next_state = (state[0], state[1] - 1)
            elif action == 3 and state[1] < GRID_SIZE - 1:  # Right
                next_state = (state[0], state[1] + 1)

            # Update Q-table using the Bellman equation
            Q_table[state][action] = (1 - LEARNING_RATE) * Q_table[state][action] + \
                LEARNING_RATE * (rewards[next_state] + DISCOUNT_FACTOR * np.max(Q_table[next_state]))

            # Transition to the next state
            state = next_state

q_learning()
print("Q_table: ")
print(Q_table)




Q_table: 
[[[ 2.81229745  2.94883667  2.63452135  4.58      ]
  [ 3.8936166   1.57628054  2.82092054  6.2       ]
  [ 5.89309671  8.          4.2497826   5.62820105]]

 [[-0.2896355   5.55007585 -0.37221283 -0.945149  ]
  [ 0.6965441   7.9597207   0.29631742  0.71      ]
  [ 5.2519291  10.          1.63648368  6.90453733]]

 [[ 0.43238179 -0.09100896  0.86443472  7.8589929 ]
  [-0.5         0.55990536  1.35954464  9.99976095]
  [ 0.          0.          0.          0.        ]]]
